apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-alerts
  labels:
  {{- include "prometheus.labels" . | nindent 4 }}
data:
  alerts.rules: {{ .Values.alerts.alertsRules | quote }}