apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-config
  labels:
  {{- include "prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.config.prometheusYml.global.scrapeInterval | quote
        }}
    rule_files:
    - alerts/alerts.rules
    - recording/recording.rules
    scrape_configs: []