apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-recording
  labels:
  {{- include "prometheus.labels" . | nindent 4 }}
data:
  recording.rules: {{ .Values.recording.recordingRules | quote }}